dist: trusty
sudo: required
language: node_js
node_js:
  - "9"
install:
  - npm install
script:
  - npm run lint
  - npm test
addons:
  chrome: stable
before_script:
  - sudo chown root /opt/google/chrome/chrome-sandbox
  - sudo chmod 4755 /opt/google/chrome/chrome-sandbox
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

