dist: trusty
language: node_js
node_js:
  - "9"
install:
  - npm install
script:
  - npm run lint
  - npm test
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

